Repository AconInc/ACON-iOS, pull requests merged in 2025-02, with the labels that each got.

#4 [FIX] 세그먼트 이동 안 하고 conduct할 시 restaurant로 post 안 하는 문제 해결 (#3)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: ❤️‍🩹 bug, 🥑 유림

#7 [FEAT] ProfileVIew UI 구현 (#5)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_arrow_right_28.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_arrow_right_28.imageset/ic_arrow_right_28.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_edit_g_20.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_edit_g_20.imageset/ic_edit_g_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_hometown_g_20.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_hometown_g_20.imageset/ic_hometown_g_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_local acon_g_20.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_local acon_g_20.imageset/ic_local acon_g_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/img_profile_basic_60.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/img_profile_basic_60.imageset/img_profile_basic_60.svg
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileBoxComponent.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
Labels: 🌀 feature, 🥑 유림

#9 [FEAT] 프로필 뷰 - 로그인 모달, 클로저 / 프로필 편집 뷰 - UI, 유효성 검사 로직 구현
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_error_20.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_error_20.imageset/ic_error_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_local check mark_20.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_local check mark_20.imageset/ic_local check mark_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile img_edit.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile img_edit.imageset/ic_profile img_edit.svg
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Type/DayOfMonthType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Type/ProfileValidMessageType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileBoxComponent.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditTextField.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditValidMessageView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileImageEditButton.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: 🌀 feature, 🥑 유림

#16 [FEAT] 프로필 편집 뷰 - 저장 로직 구현 (+ 컴포넌트 UI 수정)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileBoxComponent.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: 🌀 feature, 🥑 유림

#13 [FEAT] 커스텀 앨범 구현 (#6)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Presentation/Album/Model/AlbumModel.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/Cell/PhotoCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoCollectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/Type/PhotoCollectionViewSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
Labels: 🌀 feature, 🍓 수민

#15 [FEAT] 프로필 설정 뷰 UI (#14)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UITableViewCell+.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_arrow_right_g_20.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_arrow_right_g_20.imageset/and_ic_arrow_right_g_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_go_onboarding.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_go_onboarding.imageset/ic_profile_go_onboarding.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_logout.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_logout.imageset/ic_profile_logout.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_privacypolicy.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_privacypolicy.imageset/ic_profile_privacypolicy.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_termsofuse.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_termsofuse.imageset/ic_profile_termsofuse.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_version.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_version.imageset/ic_profile_version.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_withdraw.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_profile_withdraw.imageset/ic_profile_withdraw.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_setting_w_28.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_setting_w_28.imageset/ic_setting_w_28.svg
  ACON-iOS/ACON-iOS/Global/Service/AppVersionManager.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Type/SettingType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Cell/SettingTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
Labels: 🌀 feature, 🍓 수민

#20 [CHORE] 추천 장소 리스트 뷰 - 맵뷰, 현위치 버튼 숨김 (#19)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
Labels: 🍋‍🟩 chore, 🥑 유림

#21 [CHORE] 프로필 뷰 - 도토리 개수 UI 수정 (#18)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
Labels: 🍋‍🟩 chore, 🥑 유림

#23 [REFACTOR] 법정동 API 대신 CL Geocoder 사용 (#17)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListService.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
Labels: 🍀 refactor, 🥑 유림

#33 [FEAT] 토큰 재발급 API 연결 (#31)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Service/AuthManager.swift
  ACON-iOS/ACON-iOS/Network/Auth/AuthService.swift
  ACON-iOS/ACON-iOS/Network/Auth/AuthTargetType.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostReissueRequest.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostReissueResponse.swift
  ACON-iOS/ACON-iOS/Network/Base/BaseService.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/ViewModel/OnboardingViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: ⚪️ network, 🍓 수민

#30 [FIX] 추천장소리스트 API 옵셔널 처리 (#26)
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListRequest.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Model/SpotListFilterModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: ❤️‍🩹 bug, 🍀 refactor, 🥑 유림

#36 [FEAT] 내 프로필 조회 API 연결 (#24)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Utils/Enums/HeaderType.swift
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/Profile/DTO/GetProfileResponse.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileService.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: ⚪️ network, 🥑 유림

#38 [Fix] 리이슈에 실패했을 경우 Splash로 이동 전에 UserDefaults 토큰 삭제 (#37)
  ACON-iOS/ACON-iOS/Global/Service/AuthManager.swift
Labels: ❤️‍🩹 bug, 🥑 유림

#39 [FEAT] 로그아웃 로직 및 API 연결 (#35)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift
  ACON-iOS/ACON-iOS/Network/Auth/AuthService.swift
  ACON-iOS/ACON-iOS/Network/Auth/AuthTargetType.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLogoutRequest.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
Labels: 🌀 feature, ⚪️ network, 🥑 유림

#44 [CHORE] 인증동네 분리에 따른 UI 변경사항 적용 (#43)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_town sign up.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/ic_town sign up.imageset/ic_town sign up.svg
  ACON-iOS/ACON-iOS/Presentation/Profile/Type/SettingType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#41 [FEAT] 프로필 사진 수정 UI 구현 (#22)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/cmp_profile_selected img_layout.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/cmp_profile_selected img_layout.imageset/cmp_profile_selected img_layout.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/img_profile_basic_80.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/img_profile_basic_80.imageset/img_profile_basic_80.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/skeleton_empty_album.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Profile/skeleton_empty_album.imageset/skeleton_empty_album.svg
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ACSheetDetentType.swift
  ACON-iOS/ACON-iOS/Global/Utils/SheetUtils.swift
  ACON-iOS/ACON-iOS/Presentation/Album/Model/AlbumModel.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/AlbumTableViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/Cell/AlbumTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoCollectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoSelectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileImageEditButton.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
Labels: 🌀 feature, 🍓 수민

#51 [FEAT] 닉네임 유효성 검증 API 연결 (#49)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Network/Profile/DTO/GetNicknameValidityRequestQuery.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileService.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: ⚪️ network, 🥑 유림

#50 [FEAT] PresignedURL 획득 API 연결 (#45)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Utils/Enums/HeaderType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ImageType.swift
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/Image/DTO/GetPresignedURLRequest.swift
  ACON-iOS/ACON-iOS/Network/Image/DTO/GetPresignedURLResponse.swift
  ACON-iOS/ACON-iOS/Network/Image/DTO/PutImageToPresignedURLRequest.swift
  ACON-iOS/ACON-iOS/Network/Image/ImageService.swift
  ACON-iOS/ACON-iOS/Network/Image/ImageTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Album/Model/AlbumModel.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoSelectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: ⚪️ network, 🍓 수민

#40 [FEAT] 탈퇴 ui (#34)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/SceneDelegate.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Withdrawal/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Withdrawal/circle.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Withdrawal/circle.imageset/circle.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Withdrawal/fillCircle.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Withdrawal/fillCircle.imageset/fillCircle.svg
  ACON-iOS/ACON-iOS/Presentation/Base/BaseTabelViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/Cell/WithdrawalTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/CustomTextFieldView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalTableView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/ViewModel/WithdrawalViewModel.swift
Labels: 🌀 feature, 😎 재현

#53 [FEAT] 인증동네 수정 UI를 프로필 편집에서 프로필 설정으로 분리, API 연결 (#42)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertTitleAndButtonsView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertTitleAndButtonsViewController.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/GetVerifiedAreaListResponse.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/LocalVerificationService.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/LocalVerificationTargetType.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/Type/LocalVerificationFlowType.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationEditViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/LabelBoxWithDeletableButton.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: 🌀 feature, ⚪️ network, 🥑 유림

#55 [FEAT] 닉네임 유효성 검증 시 로딩 로띠 활성화 (#54)
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditTextField.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
Labels: 🌀 feature, 🥑 유림

#57 [FEAT] Withdrawal network (#46)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Settings/Config/Debug.xcconfig
  ACON-iOS/ACON-iOS/Global/Settings/Config/Release.xcconfig
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/Withdrawal/DTO/WithdrawalRequest.swift
  ACON-iOS/ACON-iOS/Network/Withdrawal/WithdrawalService.swift
  ACON-iOS/ACON-iOS/Network/Withdrawal/WithdrawalTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalTableView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/ViewModel/WithdrawalViewModel.swift
Labels: ⚪️ network, 😎 재현

#59 [CHORE] 닉네임 유효성 판단 기준 수정 (#58)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Settings/Config/Debug.xcconfig
  ACON-iOS/ACON-iOS/Global/Settings/Config/Release.xcconfig
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: 🍋‍🟩 chore, 🥑 유림

#60 [FEAT] 프로필 수정 API 연결 (#56)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Network/Profile/DTO/PatchProfileRequest.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileService.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: ⚪️ network, 🍓 수민, 🥑 유림

#66 [CHORE] 로딩 버튼 컴포넌트 생성, SpotListFilter 적용하기 버튼 로딩 설정 (#65)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/LoadingAnimatedButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🍋‍🟩 chore, 🌀 feature, 🥑 유림

#64 [CHORE] Sprint 2 1차 QA 준비 (#62)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/AppDelegate.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/DummyComponent.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#63 [FEAT] 기본 에러 뷰 UI 구현 (#61)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/BaseIcon/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/BaseIcon/ic_error_1_140.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/BaseIcon/ic_error_1_140.imageset/ic_error_1_140.svg
  ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift
Labels: 🌀 feature, 🥑 유림

#68 [FIX] 1차 QA 대응 - 유림 (#67)
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Type/ProfileValidMessageType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditValidMessageView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: ❤️‍🩹 bug, 🥑 유림

#75 [HOTFIX] 탈퇴 안 되는 에러 수정 (#74)
  ACON-iOS/ACON-iOS/Presentation/Base/BaseView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/Cell/WithdrawalTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/ViewModel/WithdrawalViewModel.swift
Labels: 🆘 hotfix, 🍓 수민

#73 [FIX] CustomTextFieldview layout problem (#70)
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/CustomTextFieldView.swift
Labels: ❤️‍🩹 bug, 😎 재현

#77 [FEAT] 법정동 API 연결, 서비스 불가 지역 대응 (#76)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift
  ACON-iOS/ACON-iOS/Network/Profile/DTO/GetNicknameValidityRequest.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileService.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/GetDongRequest.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/GetDongResponse.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListService.swift
  ACON-iOS/ACON-iOS/Network/SpotList/SpotListTargetType.swift
  ACON-iOS/ACON-iOS/Network/Upload/UploadTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListErrorType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/Type/ReviewVerificationErrorType.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: 🌀 feature, 🥑 유림

#79 [FIX] 2차 QA 준비 및 2차 QA 대응 - 수민 (#78)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Utils/Enums/HeaderType.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: ❤️‍🩹 bug, 🍓 수민

#84 [FIX] 2차 QA Withdrawal (#83)
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/Cell/WithdrawalTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/CustomTextFieldView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalTableView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/ViewModel/WithdrawalViewModel.swift
Labels: ❤️‍🩹 bug, 😎 재현

#85 [FEAT] 외국 위/경도일 때 동네인증 & 네이버 길찾기 분기처리 (#82)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Utils/LocationUtils.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
Labels: 🌀 feature, 🍓 수민

#87 [FIX] 2차 QA 대응 (SpotList 에러뷰) - 유림 (#81)
  ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListErrorType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
Labels: ❤️‍🩹 bug, 🥑 유림

#89 [FIX] SpotList DTO 변경사항 반영 (#88)
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListRequest.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Model/SpotListFilterModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
Labels: ⚪️ network, 🥑 유림

#91 [CHORE] 3차 QA 준비 및 반영 (#86)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Utils/ACLocationManager.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLoginResponse.swift
  ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#94 [FEAT] AmplitudeLiterals 구현 (#92)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/AmplitudeLiterals.swift
Labels: 🌀 feature, 🍓 수민

#95 [FEAT] 앰플리튜드 붙이기 - 유림 (#93)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, 🥑 유림

#96 [FEAT] 엠플리튜드 붙이기 - 수민 (#90)
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/AmplitudeLiterals.swift
  ACON-iOS/ACON-iOS/Global/Service/AmplitudeManager.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
Labels: 🌀 feature, 🍓 수민

#98 [FEAT] 출시 준비 작업 및 애플 피드백 반영 (#97)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS.xcodeproj/xcshareddata/xcschemes/ACON-iOS.xcscheme
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalView.swift
  ACON-iOS/ACON-iOS/Global/Utils/ACLocationManager.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
Labels: 🌀 feature, 🍓 수민
