Repository AconInc/ACON-iOS, pull requests merged in 2025-06, with the labels that each got.

#163 [FEAT] 홈 - 장소 이미지 색상 추출 및 그림자 추가 (#158)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIImage+.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/GlassmorphismType.swift
  ACON-iOS/ACON-iOS/Global/Utils/ShadowColorCache.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🌀 feature, 🥑 유림

#165 [FEAT] 프로필 편집 UI, 닉네임 유효성 로직 수정 / GlassBorder 리팩토링 (#164)
  ACON-iOS/ACON-iOS/Global/Extensions/UIView+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/1.0/Basic/ic_error.imageset/ic_error_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/1.0/Basic/ic_local_check_mark.imageset/ic_local check mark_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_exclamation_mark.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_exclamation_mark.imageset/ic_exclamation_mark.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_success.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_success.imageset/ic_success.svg
  ACON-iOS/ACON-iOS/Global/UIComponents/ACTextField.swift
  ACON-iOS/ACON-iOS/Network/Profile/DTO/PatchProfileRequest.swift
  ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Type/ProfileValidMessageType.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditValidMessageView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
Labels: 🍋‍🟩 chore, ⚪️ network, 🍀 refactor, 🥑 유림

#180 [CHORE] 홈, 프로필 편집 QA 반영 (#179)
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: ❤️‍🩹 bug, 🍋‍🟩 chore, 🥑 유림

#182 [FEAT] 이미지 로드 실패 UI - 홈, 장소 상세, 메뉴판 (#170)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/String+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UILabel+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UIView+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/appIcon_250603.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/appIcon_250610.png
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/MenuCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/SpotDetailImageCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotImageStatusType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/NoMatchingSpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotNoImageContentView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/TempSpotListErrorView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/Gemfile.lock
Labels: 🌀 feature, 🥑 유림

#185 [CHORE] 프로필 QA 반영 및 광고 로직 개선 (#181)
  ACON-iOS/ACON-iOS/Global/Service/GoogleAdsManager.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/GoogleAdsType.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/Cell/PhotoCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoCollectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileGoogleAdView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListGoogleAdCollectionViewCell.swift
Labels: 🍋‍🟩 chore, 🍓 수민

#191 [FEAT] 스켈레톤 애니메이션 구현 (#187)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIView+.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Cell/SavedSpotCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/SavedSpotView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/SavedSpotsViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotImageStatusType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/NoMatchingSpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewHeader.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListGoogleAdCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListSkeletonHeader.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
Labels: 🌀 feature, 🥑 유림

#193 [FIX] 메뉴판 핀치 영역, 필터 바텀시트 UI 수정 (+ '장소'탭 선택 시 로직 구현) (#192)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ACSheetDetentType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/MenuCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotFilterType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
Labels: ❤️‍🩹 bug, 🍋‍🟩 chore, 🥑 유림

#196 [FEAT] 자전거 길찾기 네이버맵 연동, 기타 오류 해결 (#195)
  ACON-iOS/ACON-iOS/Global/Utils/MapRedirect/AppleMapService.swift
  ACON-iOS/ACON-iOS/Global/Utils/MapRedirect/MapRedirectManager.swift
  ACON-iOS/ACON-iOS/Global/Utils/MapRedirect/MapServiceProtocol.swift
  ACON-iOS/ACON-iOS/Global/Utils/MapRedirect/NaverMapService.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/TransportModeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/NoMatchingSpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: ❤️‍🩹 bug, 🌀 feature, 🥑 유림

#200 [FEAT] 2.0 수정된 API 반영 (#190)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/GetVerifiedAreaListResponse.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/PostLocalAreaRequest.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/PostLocalAreaResponse.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/DTO/PostRepaceLocalAreaRequest.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/LocalVerificationService.swift
  ACON-iOS/ACON-iOS/Network/LocalVerification/LocalVerificationTargetType.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/DTO/OnboardingRequest.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/DTO/PutOnboardingRequest.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/OnboardingService.swift
  ACON-iOS/ACON-iOS/Network/Onboarding/OnboardingTargetType.swift
  ACON-iOS/ACON-iOS/Network/Profile/DTO/GetProfileResponse.swift
  ACON-iOS/ACON-iOS/Network/Profile/DTO/GetSavedSpotsResponse.swift
  ACON-iOS/ACON-iOS/Network/Upload/DTO/GetSearchSuggestionResponse.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/Type/LocalVerificationErrorType.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/Type/LocalVerificationFlowType.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationEditViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/Model/OnboardingModel.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: 🌀 feature, ⚪️ network, 🍓 수민

#209 [FEAT] 스와이프 뒤로가기 구현 및 2차 QA 준비 (#207)
  ACON-iOS/ACON-iOS/Global/Service/GoogleAdsManager.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/AlbumTableViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoCollectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoSelectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileGoogleAdView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/SavedSpotsViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/MenuImageSlideViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: 🌀 feature, 🍓 수민

#211 [FIX] 2차 QA 대응 및 Amplitude 설정 (#210)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/AmplitudeLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_exclamation_mark.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/UIComponents/NetworkErrorView.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/SpotDetailService.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/SpotDetailTargetType.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListResponse.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailMoreViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/NoMatchingSpotListItemSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListErrorType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/NoMatchingSpotHeader.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotFilterType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: ❤️‍🩹 bug, 🍋‍🟩 chore, 🥑 유림

#219 [FIX] 광고 삽입 인덱스 수정, 광고 configure 시 스켈레톤 숨기기 (#217)
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListGoogleAdCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotListCollectionViewFlowLayout.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🆘 hotfix, 🥑 유림

#222 [RELEASE] v2.0.0 업데이트 (#221)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/fastlane/Fastfile
  README.md
Labels: 🍓 수민, 🥑 유림, 💭 release
