Repository AconInc/ACON-iOS, pull requests merged in 2025-08, with the labels that each got.

#240 [FEAT] 장소 업로드 - 사진등록, 성공 페이지 구현 (AlbumVC 분기처리) (#239)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_delete.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_delete.imageset/ic_delete.svg
  ACON-iOS/ACON-iOS/Global/UIComponents/ACAlert/Type/ACAlertType.swift
  ACON-iOS/ACON-iOS/Presentation/Album/Type/AlbumFlowType.swift
  ACON-iOS/ACON-iOS/Presentation/Album/Type/PhotoCollectionViewSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/AlbumTableViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/Cell/AlbumTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/Cell/PhotoCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoCollectionViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/Type/SpotUploadSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/Cell/SpotUploadOptionCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/Cell/SpotUploadPhotoCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/MenuRecommendationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/SpotUploadPhotoViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/SpotUpload/SpotUploadSuccessViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/SpotUpload/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/ViewModel/SpotUploadViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: 🌀 feature, 🥑 유림

#252 [FIX] 2.1.0 QA 관련 작업 및 취향탐색 여부에 따른 네비게이션 분기처리 (#248)
  ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Service/AuthManager.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACAlert/Type/ACAlertType.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLoginResponse.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/ViewModel/LocalVerificationViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Splash/View/SplashViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/SpotUploadSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/SpotUpload/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/Cell/SearchSuggestionCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
Labels: ❤️‍🩹 bug, 🌀 feature, 🍓 수민

#253 [FEAT] 장소 업로드 API 구현 (#251)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/UIComponents/ACAlert/Type/ACAlertType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ImageType.swift
  ACON-iOS/ACON-iOS/Network/Base/ACService.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListRequest.swift
  ACON-iOS/ACON-iOS/Network/SpotUpload/DTO/PostSpotUploadRequest.swift
  ACON-iOS/ACON-iOS/Network/SpotUpload/SpotUploadService.swift
  ACON-iOS/ACON-iOS/Network/SpotUpload/SpotUploadTargetType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/Type/SpotUploadType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/SpotUploadPhotoViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/SpotUploadSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/ValueRatingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/SpotUpload/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/ViewModel/SpotUploadViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: ⚪️ network, 🥑 유림

#255 [FEAT] 장소 업로드 - fade in + slide 애니메이션 구현 (#254)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIView+.swift
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/UIComponents/ACAlert/Type/ACAlertType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/Type/SpotUploadType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/BaseUploadInquiry/BaseUploadInquiryView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/BaseUploadInquiry/BaseUploadInquiryViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/InquiryPages/MenuRecommendationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/SpotUpload/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewMenuRecommendationViewController.swift
Labels: 🌀 feature, 🥑 유림

#257 [CHORE] 지역 인증 - 건너뛰기 버튼을 onboarding시에만 활성화 (#256)
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Service/AuthManager.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerificationReminderViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: ❤️‍🩹 bug, 🍋‍🟩 chore, 🥑 유림

#264 [CHORE] 변경사항 적용: 앱 displayName, 필터뷰 태그, 장소업로드 성공뷰 (#262)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/success.json
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotFilterType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotUpload/View/SpotUpload/SpotUploadSuccessViewController.swift
Labels: 🍋‍🟩 chore, 🥑 유림

#266 [CHORE] 2.1.1 QA 및 릴리즈 (#265)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/Tutorial/TutorialPages/LimitedSpotsTutorialViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/Tutorial/TutorialPages/ReviewTutorialViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/Tutorial/TutorialPages/StartNowViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/ViewModel/WithdrawalViewModel.swift
Labels: 🍋‍🟩 chore, 🥑 유림, 💭 release
