Repository AconInc/ACON-iOS, pull requests merged in 2025-05, with the labels that each got.

#128 [FEAT] 2.0 홈화면 컬렉션뷰 스크롤 인터렉션, 셀 UI 2.0 업데이트 (+Button, Image 메소드 구현) (#119)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIButton+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UIImage+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/tag_local.colorset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Colors/tag_new.colorset/Contents.json
  ACON-iOS/ACON-iOS/Global/Utils/ScreenUtils.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListItemSizeType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotTagType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewHeader.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SkeletonView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotTagButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListCollectionViewFlowLayout.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
Labels: 🌀 feature, 🥑 유림

#131 [FEAT] 2.0 홈, 필터뷰 UI 업데이트 (#129)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIButton+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Protocols/ACButtonType.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACButton.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/GlassButtonType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/FloatingButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotToggleButtonView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSegmentedControl.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/FilterTagButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/SpotFilterTagStackView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
Labels: 🌀 feature, 🥑 유림

#145 [FEAT] 2.0 업로드 UI (#142)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/String+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/finishedUpload.json
  ACON-iOS/ACON-iOS/Global/UIComponents/ACTextField.swift
  ACON-iOS/ACON-iOS/Global/Utils/ScreenUtils.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/Type/ACTabBarItemType.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/Model/UploadModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/Cell/SearchKeywordCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/Cell/SearchSuggestionCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SearchEmptyView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotSearchViewModel.swift
Labels: 🌀 feature, 🍓 수민

#151 [FEAT] 2.0 장소 리스트, 장소 상세 - API 연결, 로직 개선, UI 구현(이미지없는장소, 로그인잠금) (#147)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Images/2.0/img_spot_no_image_background.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Images/2.0/img_spot_no_image_background.imageset/img_spot_no_image_background.png
  ACON-iOS/ACON-iOS/Global/Utils/Enums/GlassmorphismType.swift
  ACON-iOS/ACON-iOS/Network/SpotDetail/DTO/GetSpotDetailResponse.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListRequest.swift
  ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListResponse.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/Model/SpotDetailModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/MenuCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/Cell/SpotDetailImageCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Model/SpotModel.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotTagType.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewFooter.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/LoginLockOverlayView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotNoImageContentView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotTagButton.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/TempSpotListErrorView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
Labels: 🌀 feature, ⚪️ network, 🥑 유림

#153 [FEAT] 2.0 프로필 UI 및 탭바 UI (#149)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/UIView+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/1.0/RadioButton/ic_radio.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/1.0/RadioButton/ic_radio.imageset/ic_radio_20.svg
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio.imageset/Radio@2x.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio.imageset/Radio@3x.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio.imageset/ic_radio.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio_selected.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio_selected.imageset/Radio@2x-1.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio_selected.imageset/Radio@3x-1.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/2.0/ic_radio_selected.imageset/ic_radio_selected.png
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop1Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop2Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop3Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop4Acorn.json
  ACON-iOS/ACON-iOS/Global/Resources/Lottie/drop5Acorn.json
  ACON-iOS/ACON-iOS/Global/UIComponents/ACAlert/View/ACAlertView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACButton.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToast/Type/ACToastType.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToast/View/ACToastController.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToast/View/ACToastView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToastController.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/GlassmorphismView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ACSheetDetentType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/GlassButtonType.swift
  ACON-iOS/ACON-iOS/Global/Utils/GlassBorderAttributes.swift
  ACON-iOS/ACON-iOS/Global/Utils/ScreenUtils.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationView.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/OnboardingView.swift
  ACON-iOS/ACON-iOS/Presentation/Onboarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileBoxComponent.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift
  ACON-iOS/ACON-iOS/Presentation/TabBar/Type/ACTabBarItemType.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/Cell/SearchKeywordCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/Cell/WithdrawalTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/CustomTextFieldView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalTableView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
Labels: 🌀 feature, 🍓 수민
