Repository AconInc/ACON-iOS, pull requests merged in 2025-04, with the labels that each got.

#106 [CHORE] 프로필 관련 코드 정리 - 접근제어자, 주석 등 (#104)
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Cell/SettingTableViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/LabelBoxWithDeletableButton.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileBoxComponent.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditValidMessageView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileImageEditButton.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
Labels: 🍋‍🟩 chore, 🥑 유림

#103 [REFACTOR] ACTextField 컴포넌트 구현 및 교체 (#102)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Upload/ic_dismiss_circle_gray.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Upload/ic_dismiss_circle_gray.imageset/ic_dissmiss_circle_gray.svg
  ACON-iOS/ACON-iOS/Global/UIComponents/ACTextField.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/LabelBoxWithDeletableButton.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditTextField.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchView.swift
  ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift
Labels: 🍀 refactor, 🥑 유림

#107 [SETTING] Firebase Crashlytics 적용 (#101)
  .gitignore
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Application/AppDelegate.swift
Labels: ⚙️ setting, 🍓 수민

#110 [SETTING] Fastlane CICD 적용 (#109)
  .gitignore
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/Gemfile
  ACON-iOS/Gemfile.lock
  ACON-iOS/fastlane/Appfile
  ACON-iOS/fastlane/Fastfile
  ACON-iOS/fastlane/Matchfile
Labels: ⚙️ setting, 🍓 수민

#114 [SETTING] (2.0) 스타일 업데이트 - 폰트, global 컴포넌트, 앱 아이콘 (#112)
  ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj
  ACON-iOS/ACON-iOS/Global/Extensions/Character+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/String+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UIButton+.swift
  ACON-iOS/ACON-iOS/Global/Extensions/UILabel+.swift
  ACON-iOS/ACON-iOS/Global/Literals/StringLiterals.swift
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/acon_app_icon.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/icon_2.0.0.png
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/Basic 2.0/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/Basic 2.0/ic_clear.imageset/Contents.json
  ACON-iOS/ACON-iOS/Global/Resources/Assets.xcassets/Icons/Basic 2.0/ic_clear.imageset/ic_clear.svg
  ACON-iOS/ACON-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  ACON-iOS/ACON-iOS/Global/Resources/Fonts/Pretendard-Light.otf
  ACON-iOS/ACON-iOS/Global/Resources/Fonts/Pretendard-Medium.otf
  ACON-iOS/ACON-iOS/Global/Settings/Info.plist
  ACON-iOS/ACON-iOS/Global/UIComponents/ACTextField.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/ACToastController.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertImageView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertTitleAndButtonsView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/View/CustomAlertView.swift
  ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalView.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ACFontStyleType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/ACFontType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/LanguageType.swift
  ACON-iOS/ACON-iOS/Global/Utils/Enums/OldACFontStyle.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift
  ACON-iOS/ACON-iOS/Presentation/Base/BaseNavViewController.swift
  ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationView.swift
  ACON-iOS/ACON-iOS/Presentation/Login/View/LoginView.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/AnalyzingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/BigBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/LongBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/Cell/SmallBoxViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift
  ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailView.swift
  ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift
  ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListCollectionViewCell.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/Component/CustomSegmentedControl.swift
  ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterView.swift
  ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
Labels: ⚙️ setting, 🥑 유림
